# Generated by Django 5.2.4 on 2025-08-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_store', '0004_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
