# Generated by Django 5.2.4 on 2025-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_store', '0005_remove_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
