# Generated by Django 5.2.4 on 2025-08-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_store', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
